insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (1, 0.05, 11, 'Bicycle', 2, 1, 1);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (2, 0.02, 28, 'Car wheel', 2, 2, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (3, 0.02, 28, 'Car wheel', 2, 2, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (4, 0.02, 28, 'Car wheel', 2, 2, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (5, 0.02, 28, 'Car wheel', 2, 2, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (6, 0.3, 150, 'Bike', 2, 3, 3);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (7, 0.5, 200, 'Large bike', 2, 4, 4);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (8, 0.01, 14, 'Car wheel', 2, 4, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (9, 0.01, 14, 'Car wheel', 2, 4, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (10, 0.02, 28, 'Car wheel', 2, 5, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (11, 0.02, 28, 'Car wheel', 2, 5, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (12, 0.02, 28, 'Car wheel', 2, 5, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (13, 0.02, 28, 'Car wheel', 2, 5, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (14, 0.05, 10, 'Bicycle', 2, 6, 1);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (15, 0.05, 12, 'Bicycle', 2, 6, 1);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (16, 0.05, 9, 'Bicycle', 2, 6, 1);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (17, 0.05, 10, 'Nightstand', 2, 7, 5);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (18, 0.8, 170, 'Wardrobe', 2, 8, 6);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (19, 0.1, 15, 'Nightstand', 2, 9, 5);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (20, 0.05, 11, 'Bicycle', 2, 10, 1);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (21, 0.4, 15, 'Armchair', 2, 11, 9);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (22, 0.4, 15, 'Armchair', 2, 11, 9);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (23, 0.15, 20, 'Table', 2, 11, 10);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (24, 0.02, 28, 'Car wheel', 2, 12, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (25, 0.02, 28, 'Car wheel', 2, 12, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (26, 0.02, 28, 'Car wheel', 2, 12, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (27, 0.02, 28, 'Car wheel', 2, 12, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (28, 0.2, 70, 'Small bike', 2, 13, 2);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (29, 0.35, 150, 'Safe', 2, 14, 7);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (30, 0.05, 11, 'Bicycle', 2, 15, 1);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (31, 0.02, 28, 'Car wheel', 2, 16, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (32, 0.02, 28, 'Car wheel', 2, 16, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (33, 0.02, 28, 'Car wheel', 2, 16, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (34, 0.02, 28, 'Car wheel', 2, 16, 8);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (35, 0.65, 150, 'Wardrobe', 2, 17, 6);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (36, 0.15, 20, 'Nightstand', 2, 17, 5);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (37, 0.40, 190, 'Safe', 2, 18, 7);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (38, 0.15, 20, 'Table', 2, 19, 10);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (39, 0.15, 20, 'Table', 2, 19, 10);
insert into item (itemid, volume, mass, type, storagestatus, orderid, tarifid) values (40, 0.06, 15, 'Bicycle', 2, 20, 1);
